try:
    In=input()
    #print(in/2)
except Exception as err:
    print(err)